### PR TITLE
add korean translation

### PR DESCRIPTION
**Pull request by hyungtaklee**
Hi, I added korean translation for korean users.

This program is well known in Korea.
This is because, Korean government started SNI-based https monitoring.

This pull request includes 

lang_ko.ts
lang_ko.qm
and modification of language selection part in main.cpp

### CODE REVIEW

**Comment by Include-sys** [comment]
Hello,

Thank you for your contribution, I will add to it and build a new release at this weekend.

**Comment by bora-dong** [comment]
Your welcome.

If you want to ask something about Korean translation, you can contact me
to this email address.
Thank you for making wonderful program. It helped many Korean who suffered
from Korean government's censorship.

2019년 2월 13일 (수) 오전 6:44, include <notifications@github.com>님이 작성:

**Comment by sosoccm** [comment]
감사합니다. 선생님 ㅠㅠ 😭😭😭😭

**Comment by deuxdoom** [comment]
> Hello,
> 
> Thank you for your contribution, I will add to it and build a new release at this weekend.

thx for fast feedback!

**Comment by chaseerz** [comment]
이거 한글로 어찌 바꾸나요?

**Comment by hyungtaklee** [comment]
> 이거 한글로 어찌 바꾸나요?

아마 제작자분이 merge하셨으니까 다음 버전부터 적용이 될 것 같습니다.

https://github.com/bora-dong/GUI-for-GoodbyeDPI/releases
우선은 이쪽에서 한글화가 적용된 버전을 받으시면 됩니다.

또는 소스코드를 이용하여 적용을 하신다면 Qt Creater에서 resources/res.qrc/ 아래에 lang_ko.qm을 추가하신 후 빌드를 하시면 한글화가 적용이 됩니다.

**Comment by Include-sys** [comment]
I released new version.

https://github.com/Include-sys/GUI-for-GoodbyeDPI/releases/tag/v1.0.3

**Pull request merged**
